#!/bin/bash
## Required PBS Directives --------------------------------
#PBS -A ERDCV0089CDAG
#PBS -q debug
#PBS -l select=1:ncpus=192:mpiprocs=2
#PBS -l walltime=1:00:00
#PBS -l application=automl_zero
#PBS -j oe

# qsub -A ERDCV0089CDAG -q debug -l select=1:ncpus=192:mpiprocs=2 -l walltime=1:00:00 -l application=automl_zero -j oe -I

cd $WORK/rditljtd/automl_zero && \
source $HOME/.bashrc && \
for ((i=0; i<100; i++)); do ./run_baseline_full_debug_nobuild.sh >> experiments/baseline_full_debug/$i.out & wait & done;
